version: '3.8'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081" # Swagger UI
    environment:
      - SPRING_COUCHBASE_CONNECTION_STRING=couchbase://couchbase
      - SPRING_COUCHBASE_USERNAME=Administrator
      - SPRING_COUCHBASE_PASSWORD=password
      - SPRING_COUCHBASE_BUCKET_NAME=todo-app
      - SPRING_COUCHBASE_BUCKET_CREATE=true
      - SPRING_COUCHBASE_BUCKET_RAM_QUOTA_MB=100
      - SPRING_COUCHBASE_BUCKET_REPLICAS=0
      - SPRING_COUCHBASE_BUCKET_FLUSH_ENABLED=true
    depends_on:
      - couchbase
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  couchbase:
    image: couchbase/server:community-7.2.3
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      - COUCHBASE_INDEX_MEMORY_QUOTA=256
      - COUCHBASE_FTS_MEMORY_QUOTA=256
      - COUCHBASE_EVENTING_MEMORY_QUOTA=256
      - COUCHBASE_QUERY_MEMORY_QUOTA=256
      - COUCHBASE_SERVICES=data,index,query,fts,eventing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/ui/index.html"]
      interval: 5s
      timeout: 5s
      retries: 5

  couchbase-init:
    image: couchbase/server:community-7.2.3
    entrypoint: /opt/couchbase/bin/couchbase-cli
    command: >-
      cluster-init
      --cluster-username=Administrator
      --cluster-password=password
      --cluster-ramsize=512
      --cluster-index-ramsize=256
      --cluster-fts-ramsize=256
      --cluster-eventing-ramsize=256
      --cluster-query-ramsize=256
      --services=data,index,query,fts,eventing
      --cluster-username=Administrator
      --cluster-password=password
    depends_on:
      couchbase:
        condition: service_healthy

networks:
  todo-network:
    driver: bridge