app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours in milliseconds

couchbase:
  connection-string: ${SPRING_COUCHBASE_CONNECTION_STRING}
  username: ${SPRING_COUCHBASE_USERNAME}
  password: ${SPRING_COUCHBASE_PASSWORD}
  bucket:
    name: ${SPRING_COUCHBASE_BUCKET_NAME}
